### ISSUE TITLE
Reconciliation - High update count - config_component_relationships

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#1470]
With only 1 or 2 config/component insertions a minute there are up to 100/min to the relationships table

**Comment by adityathebe** [comment]
@moshloop I think this isn't coming from reconciliation but rather from the the `ComponentConfigRun` job

https://github.com/flanksource/canary-checker/blob/e44f621a9f9270affe8b435bd40d15e1c9d8b7db/pkg/topology/component_config.go#L127-L132

**Comment by adityathebe** [comment]
![image](https://github.com/user-attachments/assets/60596ea3-4b52-4411-a775-f7b659f51ed5)

**Comment by adityathebe** [comment]
resolved by: https://github.com/flanksource/mission-control-registry/pull/332
