### ISSUE TITLE
Gitops actions -`&` gets replaced with ` \u0026`

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#1505]

**Comment by yashmehrotra** [comment]
Link: <AWS-Instance>/playbooks/runs/01927a85-0f54-fcf8-9807-4f8afb576987

**Comment by yashmehrotra** [comment]
Commit made: https://github.com/flanksource/aws-sandbox/pull/308/commits/ff05395c2f393144dee633b376e946d9f1633873
