### ISSUE TITLE
alert coming after `waitFor` set to 5m but the resource not unhealthy for 5 mins

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/mission-control#1515]
![image (5)](https://github.com/user-attachments/assets/a1e6f3d3-0594-4d60-b3d4-b301f32d79ed)
![image (4)](https://github.com/user-attachments/assets/bf69921c-52d7-4d3d-830c-235775a2c15e)

**Comment by adityathebe** [comment]
https://github.com/flanksource/mission-control/pull/1526
