### ISSUE TITLE
errors in notification silence filters are not surfaced out

### ISSUE THREAD

**Issue by adityathebe** [flanksource/mission-control#1611]
{"time":"2024-11-11T14:17:58.322019304Z","level":"ERROR","msg":"error consuming: failed to add notification.send event for event=config.unhealthy notification=0191ebb4-2b0d-95c5-ceed-3164c7ed44e7: failed to run filter expression(config.name == \"postgresql\" && config_type ==\"Kubernetes::StatefulSet\"): ERROR: <input>:1:32: undeclared reference to 'config_type' (in container '')\n | config.name == \"postgresql\" && config_type ==\"Kubernetes::StatefulSet\"\n | ...............................^: ERROR: <input>:1:32: undeclared reference to 'config_type' (in container '')\n | config.name == \"postgresql\" && config_type ==\"Kubernetes::StatefulSet\"\n | ...............................^"}
{"time":"2024-11-11T14:18:03.346806324Z","level":"ERROR","msg":"error consuming: failed to add notification.send event for event=config.unhealthy notification=0191ebb4-2b0d-95c5-ceed-3164c7ed44e7: failed to run filter expression(config.name == \"postgresql\" && config_type ==\"Kubernetes::StatefulSet\"): ERROR: <input>:1:32: undeclared reference to 'config_type' (in container '')\n | config.name == \"postgresql\" && config_type ==\"Kubernetes::StatefulSet\"\n | ...............................^: ERROR: <input>:1:32: undeclared reference to 'config_type' (in container '')\n | config.name == \"postgresql\" && config_type ==\"Kubernetes::StatefulSet\"\n | ...............................^"}

**Comment by moshloop** [comment]
@adityathebe  - Can we also update the docs of the fields available ?

**Comment by adityathebe** [comment]
> @adityathebe - Can we also update the docs of the fields available ?

https://github.com/flanksource/docs/issues/309
https://github.com/flanksource/flanksource-ui/issues/2403
