### ISSUE TITLE
[Saas] Add ability to download kubeconfig to talk to vcluster 

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#673]
As part of the tenant chart:
- Create a new service account with permissions only to the CRD's, Configmaps and Secrets 
- Create a service-account secret: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token

- Add an api endpoint `/api/kubeconfig` to retrieve the kubeconfig - generate it and fill in the token from the secret.
- Add an api endpoint  `/api/kube-proxy` that forward traffic to `kubernetes.default.svc` stripping off the path

**Comment by yashmehrotra** [comment]
Approach:
Support Whatever is supported by flux kustomize
Start with basic git://
Strategic merge patches to delete/whitelist

Gitops data in a mission-control table
Once added:
    - Commit back to saas-prod, use playbooks repo
    - Heart beat chart will create cm in workload mc instance
    - Create virtual scraper, insert CI
    - Add CI based events on playbook (on catalog.create update, run these, on delete remove files) see gitops playbook action template
    - Dont create obj directly, create config items
    - Using gitops playbook actions, push it saas prod
